//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-04-13 21:24:14
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------


using ZXYL.Model;
using ZXYL.DAL;

namespace ZXYL.BLL
{	
	public partial class V_PubCourse_ClassfyBLL:BaseServiceDapperContrib<Model.V_PubCourse_Classfy>
    {
     

    }
}

