//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-04-10 08:50:30
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace ZXYL.Model
{	
   
   [Table("Pub_video")]
    public partial class Pub_video
    {

	   /// <summary>
     	/// 
     	/// </summary>
		[Key]
		public int id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string name { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string videoUrl { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int? crouserId { get; set; }

		   
    }
}

