//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-04-11 20:01:48
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace ZXYL.Model
{	
   
   [Table("Pub_video")]
    public partial class Pub_video
    {

	   /// <summary>
     	/// 视频id
     	/// </summary>
		[Key]
		public int id { get; set; }

		/// <summary>
     	/// 视频名称
     	/// </summary>
		public string vName { get; set; }

		/// <summary>
     	/// 视频链接地址
     	/// </summary>
		public string videoUrl { get; set; }

		/// <summary>
     	/// 课程id
     	/// </summary>
		public int? crouserId { get; set; }

		/// <summary>
     	/// 保存路径的文件名称
     	/// </summary>
		public string videoName { get; set; }

		/// <summary>
     	/// 是否停用
     	/// </summary>
		public byte stopFlag { get; set; }

		/// <summary>
     	/// 视频创建时间
     	/// </summary>
		public DateTime? createTime { get; set; }

		/// <summary>
     	/// 视频的类型
     	/// </summary>
		public string videoType { get; set; }

		   
    }
}

