//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2020-04-13 21:22:42
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失
//     作者：Harbour CTS
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Dapper.Contrib.Extensions;

namespace ZXYL.Model
{	
   
   [Table("V_PubCourse_Classfy")]
    public partial class V_PubCourse_Classfy
    {

	   /// <summary>
     	/// 
     	/// </summary>
		public string courseName { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string imgUrl { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public decimal? price { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string courseAudit { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public int id { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string courseCode { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public byte? isFree { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public byte? isMadical { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string classfyName { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public DateTime? creatTime { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string remark { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public byte? stopFlag { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public string imgName { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public long? clickCount { get; set; }

		/// <summary>
     	/// 
     	/// </summary>
		public long? joinCount { get; set; }

		   
    }
}

